spring.application.name=reverix
spring.datasource.url=jdbc:mysql://localhost:3306/reverix_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

server.port=8080

app.jwt.secret=reverix-super-secret-jwt-key-change-this-in-production-make-it-long
app.jwt.expiration=86400000

# TMDb API
tmdb.api.key=c13156252778c43dd008292bb7e6b04d
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.image.base-url=https://image.tmdb.org/t/p/w500

gemini.api.key=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
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# Replace Gemini config with this
openrouter.api.key=your_openrouter_key_here
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions